include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: "12"
    env:
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

  - os: linux
    services: docker
    language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_script:
  - export NODE_OPTIONS=–max_old_space_size=8192

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -e GH_TOKEN=$GH_TOKEN \
        -v $PWD:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn install --link-duplicates --pure-lockfile && yarn electron-pack --win"
    elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
      npm install;
      npm run electron-pack;
    else
      security create-keychain -p $KEYCHAIN_PASSWORD build.keychain;
      security default-keychain -s build.keychain;
      security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain;
      echo $KEYSTORE | base64 --decode - > keystore.p12;
      security import keystore.p12 -k build.keychain -P $KEYCHAIN_PASSWORD -T /usr/bin/codesign;
      yarn install;
      yarn electron-pack;
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"